apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv 
  namespace: jenkins
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /srv/nfs/k8s/jenkins
    server: k9s1.rsletten.com
    readOnly: false
